### ISSUE TITLE
Storing Order Using Localstorage 

### ISSUE THREAD

**Issue by hyyan** [SortableJS/polymer-sortablejs#10]
Hey 

I have been trying to to store the order using localstroage as explained in [here](https://github.com/RubaXa/Sortable/wiki/Sortable-v1.0-%E2%80%94-New-capabilities#methods-for-sorting-acquisition-and-modification) , but that did not work at all  even though the options are stored in the localstorage .

Here is a snippet from my code : 

``` js

<dom-module id="foo-list">
    <template>
        <style>
            :host {
                display: block;
            }
        </style>

        <sortable-js store="{{store}}" group="{{group}}">
            <content></content>
        </sortable-js>
    </template>

    <script>
        Polymer({
            is: 'foo-list',
            properties: {
                group: {
                    type: String,
                    value: 'testing',
                },
                store: {
                    type: Object,
                    value: {
                        /**
                         * Get the order of elements. Called once during initialization.
                         * @param   {Sortable}  sortable
                         * @returns {Array}
                         */
                        get: function(sortable) {
                            console.log('GET :', sortable.options.group);
                            var order = localStorage.getItem(sortable.options.group.name);
                            return order ? order.split('|') : [];
                        },

                        /**
                         * Save the order of elements. Called onEnd (when the item is dropped).
                         * @param {Sortable}  sortable
                         */
                        set: function(sortable) {
                            var order = sortable.toArray();
                            console.log('SET :', sortable.options.group);
                            localStorage.setItem(sortable.options.group.name, order.join('|'));
                        }
                    }
                }
        });
    </script>
</dom-module>

```

Any idea will be helpful , Thanks in advance

**Comment by hyyan** [comment]
Sometimes I get the following error : 

```cmd
polymer-mini.html:711 Uncaught Error: The ref_node to be inserted before is not a child of this node
```

**Comment by bstmedia** [comment]
Let me share how I do it:

This how my sortable looks like. 

 `<sortable-js id="mySortList" animation="100" store="">
          <template is="dom-repeat" items="{{myList}}" as="item" >
            <div data-id$="[[item.ID]]">[[item.NAME]]</div>
          </template>
        </sortable-js>`

I'm apply the store code when the document is ready. 

`this.$.mySortList.store = {
            get: function (sortable) {
              var order = localStorage.getItem('ANYNAME');
              return order ? order.split('|') : [];
            },
            set: function (sortable) {
              var order = sortable.toArray();
              localStorage.setItem('ANYNAME', order.join('|'));
            }`

I can now drag and drop items as I wish. Each change is written to local storage. 

The saved list can be read using:

`var list = localStorage.getItem('ANYNAME');`

This works for me fine and I hope that this will help somebody else.
