### ISSUE TITLE
Handles inside a component

### ISSUE THREAD

**Issue by jermsv1** [SortableJS/polymer-sortablejs#11]
I'm trying to set a handle that's inside a component and wondering what the handle attribute should be if it allows it?

```
<sortable-js handle="mycomp.header">
    <li><mycomp></mycomp></li>
    <li><mycomp></mycomp></li>
</sortable-js>
```

Where mycomp is something like this..

```
<mycomp>
  <div class="header"></div>
  <div class="body"></div>
</mycomp>
```

Can sortable-js look inside the component's elements for the drag handler?

**Comment by gravypower** [comment]
Not sure if this is correct, but as far as I can tell it is due to the Sortable library not taking the shadow dom into account.  I wanted to do the same thing and had to make an alteration to the_onTapStart and _closest functions.

_onTapStart :  originalTarget = target > originalTarget = evt.path[0]

then I changed the _closest funtion to

``` javascript
function(el, selector, ctx) {
  if (el) {
    ctx = ctx || document;
    selector = selector.split('.');

    var tag = selector.shift().toUpperCase(),
      re = new RegExp('\\s(' + selector.join('|') + ')(?=\\s)', 'g');

    do {
      if (
        (tag === '>*' && el.parentNode === ctx) || (
          (tag === '' || el.nodeName.toUpperCase() == tag) &&
          (!selector.length || ((' ' + el.className + ' ').match(re) || []).length == selector.length)
        )
      ) {
        return el;
      }


      if(el.host != null)
      {
        el = el.host;
      }
      else
      {
        el = el.parentNode;
      }


    }
    while (el != null && el !== ctx);
  }

  return null;
}
```

I have not been able to find a way to override the functionality

**Comment by gravypower** [comment]
have forked Sortable and working on the change there. https://github.com/FurnaceCMS/Sortable

**Comment by jermsv1** [comment]
Thanks @gravypower I'll give this a shot, i figured it was a shadow dom thing.

**Comment by gravypower** [comment]
@jermsv1 have you had any issues with the changes in my fork of Sortable? I was thinking of opening up a pull request as I have not had any issues with them.

**Comment by jermsv1** [comment]
@gravypower Can't seem to get dragging working. What does your `handle` selector look like? 

should this work? 

```
handle="mycomp.header"
```

**Comment by gravypower** [comment]
This is what I am doing

`<sortable-js handle=".drag-handle"></sortable-js>`

You can see where I am using it [here](https://github.com/FurnaceCMS/furnace-app/blob/master/src/meta-collection/meta-collection-builder.html#L74)

**Comment by jermsv1** [comment]
Worked out great, haven't had any issues with it so far. Thanks

**Comment by jermsv1** [comment]
Also should submit a PR.

**Comment by gravypower** [comment]
PR open https://github.com/RubaXa/Sortable/pull/943

**Comment by gravypower** [comment]
I think we can consider this one closed now?

**Comment by jermsv1** [comment]
Yep
