### ISSUE TITLE
onRemove is fired even if we set pull = clone

### ISSUE THREAD

**Issue by sravan-s** [SortableJS/polymer-sortablejs#12]
I got a polymer element with multiple **polymer-sortablejs** elements. I set the group like this:
```
      this.uuid = Utilities.generateUUID();
        this.$.master.group = {
          name: me.uuid,
          pull: 'clone'
        }
        var slaves = this.querySelectorAll('.slaves');
        for (var i = 0; i < slaves.length; i++) {
          slaves[i].group = {
            name: me.uuid
          }
        }
```
where #master and .slaves are the sortable js elements.

MY requirement is to copy elements from master to slave.

I made a fix at  #13.

Can any one please verify?

**Comment by gutenye** [comment]
fixed by #13
