### ISSUE TITLE
Won't run because all polymer elements are in the bower_components folder

### ISSUE THREAD

**Issue by dsnowdon** [SortableJS/polymer-sortablejs#2]
GET http://localhost:8080/node_modules/polymer/polymer.html 404 (Not Found)
Sortable.js:1 Uncaught SyntaxError: Unexpected token <

Everthing for polymer is in the bower_components folder.

IE ../../bower_components/polymer/polymer.html

**Comment by gutenye** [comment]
fixed by https://github.com/SortableJS/polymer-sortablejs/commit/45b8bfca30c87f3e085fa5ca7e77db368d61ba0b

New Usage:

```
$ bower install SortableJS/polymer-sortablejs
```

If you have any problems, open this issue again.

**Comment by dsnowdon** [comment]
The docs are wrong. To import it I have to use.

<link rel="import" href="../../bower_components/sortabljs/polymer-sortablejs.html"/>

**Comment by gutenye** [comment]
Can share your code? I need more information.

Get Outlook for iOS




On Thu, Jul 14, 2016 at 12:24 PM +0800, "dsnowdon" <notifications@github.com> wrote:












The docs are wrong. To import it I have to use.

**Comment by dsnowdon** [comment]
When I download via bower it goes into the directory _bower_components/sortabljs/_ 
The readme.md says to import it form _bower_components/polymer-sortablejs/_

Its got nothing to do with my code.

**Comment by gutenye** [comment]
Run `bower install polymer-sortablejs` not `bower install sortablejs`
